# Generated by Django 3.2.12 on 2022-03-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0036_remove_existing_constraints'),
        ('versioning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurestate',
            name='environment_feature_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_states', to='versioning.environmentfeatureversion'),
        ),
        migrations.AddField(
            model_name='historicalfeaturestate',
            name='environment_feature_version',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='versioning.environmentfeatureversion'),
        ),
    ]
